### ISSUE TITLE
[Bug] Wrong data type in multi_image_reconstruction.py

### ISSUE THREAD

**Issue by sfarrens** [CEA-COSMIC/pysap-etomo#6]
When running `multi_image_reconstruction.py` I get the error `TypeError: Input is not a numpy array` coming from ModOpt. Note that I had to set 
```python
radon_op = Radon2D(angles=theta, img_size=img_size, gpu=False, n_channels=n_channels)
```
in order run this script on my laptop. The source of the problem appears to be from line 23
```python
data = radon_op.op(image)
```
where `data` is a of type `list` and not `numpy.ndarray`. Simply setting
```python
data = np.array(radon_op.op(image))
```
appears to resolve the problem, however it should be further investigated that `radon_op.op` is returning the correct type.

**Comment by Biagig** [comment]
Thanks, I did not try this reconstruction on cpu before and there was indeed an error with the data type in this case. I added the np.array inside the Radon class directly which solved the issue.
